import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { config } from './config.js';
import { parseMessage, smtp, withImap } from './email.js';

const accountSchema = z.string().default('info').describe('Configured account name, for example info');
function getAccount(name: string) { const a = config.accounts.find((x) => x.name === name); if (!a) throw new Error(`Unknown account '${name}'. Available: ${config.accounts.map((x) => x.name).join(', ')}`); return a; }
async function ensureMailbox(client: Parameters<Parameters<typeof withImap>[1]>[0], name: string) {
  const boxes = await client.list();
  const match = boxes.find((b) => b.path.toLowerCase() === name.toLowerCase() || (name.toLowerCase() === 'drafts' && /draft/i.test(b.specialUse ?? '')));
  if (!match) throw new Error(`Mailbox not found: ${name}`);
  return match.path;
}
function header(value: string) { return value.replace(/[\r\n]/g, ' ').trim(); }

export function createServer() {
  const server = new McpServer({ name: 'tradesource-email', version: '0.1.0' });
  server.registerTool('list_mailboxes', { description: 'List folders/mailboxes for an email account.', inputSchema: { account: accountSchema } }, async ({ account }) => ({ content: [{ type: 'text', text: JSON.stringify(await withImap(getAccount(account), async (c) => (await c.list()).map((b) => ({ path: b.path, specialUse: b.specialUse ?? null })))) }] }));
  server.registerTool('search_emails', { description: 'Search email headers and text. Returns compact message IDs; use get_email for full content.', inputSchema: { account: accountSchema, mailbox: z.string().default('INBOX'), from: z.string().optional(), to: z.string().optional(), subject: z.string().optional(), text: z.string().optional(), since: z.string().optional(), limit: z.number().int().min(1).max(50).default(20) } }, async (args) => { const result = await withImap(getAccount(args.account), async (c) => { const box = await ensureMailbox(c, args.mailbox); const lock = await c.getMailboxLock(box); try { const query: Record<string, unknown> = {}; if (args.from) query.from = args.from; if (args.to) query.to = args.to; if (args.subject) query.subject = args.subject; if (args.text) query.body = args.text; if (args.since) query.since = new Date(args.since); if (!Object.keys(query).length) query.all = true; const rows = []; for await (const m of c.fetch(query, { uid: true, envelope: true, flags: true }, { uid: true })) { rows.push({ uid: m.uid, subject: m.envelope?.subject ?? '', from: m.envelope?.from?.map((x) => x.address).join(', ') ?? '', date: m.envelope?.date?.toISOString() ?? null, flags: [...(m.flags ?? [])] }); if (rows.length >= args.limit) break; } return rows; } finally { lock.release(); } }); return { content: [{ type: 'text', text: JSON.stringify(result) }] }; });
  server.registerTool('get_email', { description: 'Retrieve one email by UID from a mailbox.', inputSchema: { account: accountSchema, mailbox: z.string().default('INBOX'), uid: z.number().int().positive() } }, async ({ account, mailbox: box, uid }) => { const raw = await withImap(getAccount(account), async (c) => { const lock = await c.getMailboxLock(await ensureMailbox(c, box)); try { const msg = await c.fetchOne(uid, { source: true }, { uid: true }); if (!msg?.source) throw new Error('Email not found'); return msg.source; } finally { lock.release(); } }); return { content: [{ type: 'text', text: JSON.stringify(await parseMessage(raw)) }] }; });
  server.registerTool('list_attachments', { description: 'List attachment metadata without downloading files.', inputSchema: { account: accountSchema, mailbox: z.string().default('INBOX'), uid: z.number().int().positive() } }, async ({ account, mailbox: box, uid }) => { const raw = await withImap(getAccount(account), async (c) => { const lock = await c.getMailboxLock(await ensureMailbox(c, box)); try { const msg = await c.fetchOne(uid, { source: true }, { uid: true }); if (!msg?.source) throw new Error('Email not found'); return msg.source; } finally { lock.release(); } }); return { content: [{ type: 'text', text: JSON.stringify((await parseMessage(raw)).attachments) }] }; });
  server.registerTool('create_draft', { description: 'Create a real draft in the account Drafts folder. Enabled by ALLOW_DRAFTS=true.', inputSchema: { account: accountSchema, to: z.string().optional(), subject: z.string().optional(), text: z.string().min(1), cc: z.string().optional() } }, async ({ account, to, subject, text, cc }) => { if (!config.allowDrafts) throw new Error('Drafts are disabled (set ALLOW_DRAFTS=true)'); const a = getAccount(account); const result = await withImap(a, async (c) => { const box = await ensureMailbox(c, 'Drafts'); const lines = [`From: ${header(a.address)}`, to ? `To: ${header(to)}` : '', cc ? `Cc: ${header(cc)}` : '', `Subject: ${header(subject ?? '')}`, `Date: ${new Date().toUTCString()}`, 'MIME-Version: 1.0', 'Content-Type: text/plain; charset=utf-8', 'Content-Transfer-Encoding: 8bit', '', text].filter(Boolean).join('\r\n'); return c.append(box, Buffer.from(lines, 'utf8'), ['\\Draft']); }); return { content: [{ type: 'text', text: JSON.stringify({ mailbox: 'Drafts', uid: result.uid ?? null }) }] }; });
  server.registerTool('send_email', { description: 'Send an email. Enabled by ALLOW_SEND=true.', inputSchema: { account: accountSchema, to: z.string().email(), subject: z.string().min(1), text: z.string().min(1), cc: z.string().optional() } }, async ({ account, to, subject, text, cc }) => { if (!config.allowSend) throw new Error('Sending is disabled (set ALLOW_SEND=true)'); const a = getAccount(account); const info = await smtp(a).sendMail({ from: a.address, to, cc, subject, text }); return { content: [{ type: 'text', text: JSON.stringify({ messageId: info.messageId }) }] }; });
  return server;
}
