import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { config } from './config.js';
import { appendSentCopy, appendToMailbox, buildSentMessage, createMailbox, fetchMessage, listMessageUids, moveMessage, parseMessage, parseMessageDetails, setMessageFlag, smtp, withImap } from './email.js';
import { classifySubjectAndSender, extractMandateData, isMandateSubject } from './organization.js';

const accountSchema = z.string().default('info').describe('Configured account name, for example info');
function getAccount(name: string) { const a = config.accounts.find((x) => x.name === name); if (!a) throw new Error(`Unknown account '${name}'. Available: ${config.accounts.map((x) => x.name).join(', ')}`); return a; }
async function ensureMailbox(client: Parameters<Parameters<typeof withImap>[1]>[0], name: string) {
  const boxes = await client.list();
  const specialUse = { Sent: '\\Sent', Drafts: '\\Drafts', Trash: '\\Trash' }[name];
  const match = boxes.find((b) => b.path.toLowerCase() === name.toLowerCase() || (specialUse && b.specialUse === specialUse));
  if (!match) throw new Error(`Mailbox not found: ${name}`);
  return match.path;
}
function header(value: string) { return value.replace(/[\r\n]/g, ' ').trim(); }
function ownDomain(address: string) { return address.split('@')[1] ?? ''; }
function json(value: unknown) { return { content: [{ type: 'text' as const, text: JSON.stringify(value) }] }; }

async function readParsed(account: ReturnType<typeof getAccount>, mailbox: string, uid: number) {
  const message = await fetchMessage(account, mailbox, uid);
  return { message, parsed: await parseMessageDetails(message.source!) };
}

async function resolveMailbox(account: ReturnType<typeof getAccount>, name: string, specialName?: 'Sent' | 'Drafts' | 'Trash') {
  return withImap(account, async (client) => ensureMailbox(client, specialName ?? name));
}

export function createServer() {
  const server = new McpServer({ name: 'tradesource-email', version: '0.1.0' });
  server.registerTool('list_mailboxes', { description: 'List folders/mailboxes for an email account.', inputSchema: { account: accountSchema } }, async ({ account }) => ({ content: [{ type: 'text', text: JSON.stringify(await withImap(getAccount(account), async (c) => (await c.list()).map((b) => ({ path: b.path, specialUse: b.specialUse ?? null })))) }] }));
  server.registerTool('search_emails', { description: 'Search email headers and text. Returns compact message IDs; use get_email for full content.', inputSchema: { account: accountSchema, mailbox: z.string().default('INBOX'), from: z.string().optional(), to: z.string().optional(), subject: z.string().optional(), text: z.string().optional(), since: z.string().optional(), limit: z.number().int().min(1).max(50).default(20) } }, async (args) => { const result = await withImap(getAccount(args.account), async (c) => { const box = await ensureMailbox(c, args.mailbox); const lock = await c.getMailboxLock(box); try { const query: Record<string, unknown> = {}; if (args.from) query.from = args.from; if (args.to) query.to = args.to; if (args.subject) query.subject = args.subject; if (args.text) query.body = args.text; if (args.since) query.since = new Date(args.since); if (!Object.keys(query).length) query.all = true; const rows = []; for await (const m of c.fetch(query, { uid: true, envelope: true, flags: true }, { uid: true })) { rows.push({ uid: m.uid, subject: m.envelope?.subject ?? '', from: m.envelope?.from?.map((x) => x.address).join(', ') ?? '', date: m.envelope?.date?.toISOString() ?? null, flags: [...(m.flags ?? [])] }); if (rows.length >= args.limit) break; } return rows; } finally { lock.release(); } }); return { content: [{ type: 'text', text: JSON.stringify(result) }] }; });
  server.registerTool('get_email', { description: 'Retrieve one email by UID from a mailbox.', inputSchema: { account: accountSchema, mailbox: z.string().default('INBOX'), uid: z.number().int().positive() } }, async ({ account, mailbox: box, uid }) => { const raw = await withImap(getAccount(account), async (c) => { const lock = await c.getMailboxLock(await ensureMailbox(c, box)); try { const msg = await c.fetchOne(uid, { source: true }, { uid: true }); if (!msg || !msg.source) throw new Error('Email not found'); return msg.source; } finally { lock.release(); } }); return { content: [{ type: 'text', text: JSON.stringify(await parseMessage(raw)) }] }; });
  server.registerTool('list_attachments', { description: 'List attachment metadata without downloading files.', inputSchema: { account: accountSchema, mailbox: z.string().default('INBOX'), uid: z.number().int().positive() } }, async ({ account, mailbox: box, uid }) => { const raw = await withImap(getAccount(account), async (c) => { const lock = await c.getMailboxLock(await ensureMailbox(c, box)); try { const msg = await c.fetchOne(uid, { source: true }, { uid: true }); if (!msg || !msg.source) throw new Error('Email not found'); return msg.source; } finally { lock.release(); } }); return { content: [{ type: 'text', text: JSON.stringify((await parseMessage(raw)).attachments) }] }; });
  server.registerTool('flag_email', { description: 'Set or remove an IMAP flag on a message.', inputSchema: { account: accountSchema, mailbox: z.string(), uid: z.number().int().positive(), flag: z.string().regex(/^\\[A-Za-z]+$/), enabled: z.boolean().default(true) } }, async ({ account, mailbox, uid, flag, enabled }) => json(await setMessageFlag(getAccount(account), await resolveMailbox(getAccount(account), mailbox), uid, flag, enabled)));
  server.registerTool('move_email', { description: 'Move a message to another mailbox.', inputSchema: { account: accountSchema, sourceMailbox: z.string(), uid: z.number().int().positive(), targetMailbox: z.string() } }, async ({ account, sourceMailbox, uid, targetMailbox }) => { const a = getAccount(account); return json(await moveMessage(a, await resolveMailbox(a, sourceMailbox), uid, await resolveMailbox(a, targetMailbox))); });
  server.registerTool('delete_email', { description: 'Move a message to the IMAP Trash mailbox.', inputSchema: { account: accountSchema, mailbox: z.string(), uid: z.number().int().positive() } }, async ({ account, mailbox, uid }) => { const a = getAccount(account); return json(await moveMessage(a, await resolveMailbox(a, mailbox), uid, await resolveMailbox(a, 'Trash', 'Trash'))); });
  server.registerTool('create_mailbox', { description: 'Create an IMAP mailbox if it does not exist.', inputSchema: { account: accountSchema, name: z.string().min(1) } }, async ({ account, name }) => json(await createMailbox(getAccount(account), name)));
  server.registerTool('download_attachment', { description: 'Download an email attachment as Base64.', inputSchema: { account: accountSchema, mailbox: z.string(), uid: z.number().int().positive(), attachmentIndex: z.number().int().min(0) } }, async ({ account, mailbox, uid, attachmentIndex }) => { const a = getAccount(account); const { parsed } = await readParsed(a, await resolveMailbox(a, mailbox), uid); const attachment = parsed.attachments[attachmentIndex]; if (!attachment) throw new Error(`Attachment not found at index ${attachmentIndex}`); return json({ filename: attachment.filename ?? null, contentType: attachment.contentType, size: attachment.size, base64: attachment.content.toString('base64') }); });
  server.registerTool('classify_email', { description: 'Classify an email by sender and subject.', inputSchema: { account: accountSchema, mailbox: z.string(), uid: z.number().int().positive() } }, async ({ account, mailbox, uid }) => { const a = getAccount(account); const { parsed } = await readParsed(a, await resolveMailbox(a, mailbox), uid); return json({ category: classifySubjectAndSender(parsed.subject ?? '', parsed.from?.text ?? '', ownDomain(a.address)), subject: parsed.subject ?? '', from: parsed.from?.text ?? '', uid }); });
  server.registerTool('extract_mandate_data', { description: 'Extract structured mandate fields from an email.', inputSchema: { account: accountSchema, mailbox: z.string(), uid: z.number().int().positive() } }, async ({ account, mailbox, uid }) => { const a = getAccount(account); const { parsed } = await readParsed(a, await resolveMailbox(a, mailbox), uid); if (!isMandateSubject(parsed.subject ?? '')) throw new Error('Email is not a mandate request'); return json({ uid, ...extractMandateData(parsed.text ?? '') }); });
  server.registerTool('auto_organize', { description: 'Classify and move emails into organization mailboxes.', inputSchema: { account: accountSchema, mailbox: z.string(), since: z.string().datetime() } }, async ({ account, mailbox, since }) => { const a = getAccount(account); const source = await resolveMailbox(a, mailbox); const uids = await listMessageUids(a, source, new Date(since)); const moved = []; for (const uid of uids) { const { parsed } = await readParsed(a, source, uid); const category = classifySubjectAndSender(parsed.subject ?? '', parsed.from?.text ?? '', ownDomain(a.address)); const target = { 'Neue Mandatsanfrage': 'Mandate/Neu', 'Kundenantwort': 'Mandate/Antworten', 'Versicherer-Korrespondenz': 'Versicherer', 'Spam-Verdacht': 'Spam-Verdacht', Sonstige: '' }[category]; if (!target) continue; await createMailbox(a, target); await moveMessage(a, source, uid, target); moved.push({ uid, category, target }); } return json(moved); });
  server.registerTool('find_duplicate_mandates', { description: 'Find and move duplicate mandate requests.', inputSchema: { account: accountSchema, mailbox: z.string(), since: z.string().datetime() } }, async ({ account, mailbox, since }) => { const a = getAccount(account); const source = await resolveMailbox(a, mailbox); const uids = await listMessageUids(a, source, new Date(since)); const groups = new Map<string, { uid: number; date: number }[]>(); for (const uid of uids) { const { parsed } = await readParsed(a, source, uid); if (!isMandateSubject(parsed.subject ?? '')) continue; const data = extractMandateData(parsed.text ?? ''); const key = `${data.email ?? ''}|${data.name ?? ''}`.toLowerCase(); if (!key || key === '|') continue; const date = parsed.date?.getTime() ?? 0; const group = groups.get(key) ?? []; group.push({ uid, date }); groups.set(key, group); } await createMailbox(a, 'Mandate/Duplikat'); const duplicates = []; for (const [key, group] of groups) { group.sort((left, right) => left.date - right.date); for (const duplicate of group.slice(1)) { await moveMessage(a, source, duplicate.uid, 'Mandate/Duplikat'); duplicates.push({ key, uid: duplicate.uid }); } } return json(duplicates); });
  server.registerTool('list_open_mandates', { description: 'List unread, non-duplicate mandate requests.', inputSchema: { account: accountSchema, mailbox: z.string(), since: z.string().datetime() } }, async ({ account, mailbox, since }) => { const a = getAccount(account); const source = await resolveMailbox(a, mailbox); const uids = await listMessageUids(a, source, new Date(since)); const rows = []; for (const uid of uids) { const { parsed, message } = await readParsed(a, source, uid); if (!isMandateSubject(parsed.subject ?? '') || message.flags?.has('\\Seen')) continue; const data = extractMandateData(parsed.text ?? ''); rows.push({ ...data, date: parsed.date?.toISOString() ?? null, uid }); } return json(rows); });
  server.registerTool('create_draft', { description: 'Create a real draft in the account Drafts folder. Enabled by ALLOW_DRAFTS=true.', inputSchema: { account: accountSchema, to: z.string().optional(), subject: z.string().optional(), text: z.string().min(1), cc: z.string().optional() } }, async ({ account, to, subject, text, cc }) => { if (!config.allowDrafts) throw new Error('Drafts are disabled (set ALLOW_DRAFTS=true)'); const a = getAccount(account); const result = await withImap(a, async (c) => { const box = await ensureMailbox(c, 'Drafts'); const lines = [`From: ${header(a.address)}`, to ? `To: ${header(to)}` : '', cc ? `Cc: ${header(cc)}` : '', `Subject: ${header(subject ?? '')}`, `Date: ${new Date().toUTCString()}`, 'MIME-Version: 1.0', 'Content-Type: text/plain; charset=utf-8', 'Content-Transfer-Encoding: 8bit', '', text].filter(Boolean).join('\r\n'); return c.append(box, Buffer.from(lines, 'utf8'), ['\\Draft']); }); if (!result) throw new Error('Could not create draft'); return { content: [{ type: 'text', text: JSON.stringify({ mailbox: 'Drafts', uid: result.uid ?? null }) }] }; });
  server.registerTool('send_email', { description: 'Send an email. Enabled by ALLOW_SEND=true.', inputSchema: { account: accountSchema, to: z.string().email(), subject: z.string().min(1), text: z.string().min(1), cc: z.string().optional() } }, async ({ account, to, subject, text, cc }) => { if (!config.allowSend) throw new Error('Sending is disabled (set ALLOW_SEND=true)'); const a = getAccount(account); const info = await smtp(a).sendMail({ from: a.address, to, cc, subject, text }); const messageId = info.messageId ?? `<local-${Date.now()}@${a.address.split('@')[1] ?? 'localhost'}>`; let sentCopySaved = false; let sentCopyError: string | null = null; try { await appendSentCopy(a, buildSentMessage({ from: a.address, to, cc, subject, text, messageId })); sentCopySaved = true; } catch (error) { sentCopyError = error instanceof Error ? error.message : String(error); console.error('Failed to save sent copy to the IMAP Sent mailbox:', error); } let auditLogged = false; let auditError: string | null = null; try { await createMailbox(a, 'Gesendet-Protokoll'); await appendToMailbox(a, 'Gesendet-Protokoll', Buffer.from(`timestamp=${new Date().toISOString()}\trecipient=${header(to)}\tsubject=${header(subject)}\tmessageId=${header(messageId)}\n`, 'utf8'), ['\\Seen']); auditLogged = true; } catch (error) { auditError = error instanceof Error ? error.message : String(error); console.error('Failed to write sent-mail audit log:', error); } return { content: [{ type: 'text', text: JSON.stringify({ messageId, sentCopySaved, auditLogged, ...(sentCopyError ? { sentCopyError } : {}), ...(auditError ? { auditError } : {}) }) }] }; });
  return server;
}
